<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose Password_acceptTermsAndConditions</name>
   <tag></tag>
   <elementGuidId>f8df9a25-fe07-48b8-9a67-a105c2c8ba9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptTermsAndConditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptTermsAndConditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6291f727-c8fb-4d8c-8515-029e399e8bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>721bbed1-41cb-4aad-b512-5ee19a2da14b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>86853ccf-9f6b-499f-8a4c-ec8ea1713ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptTermsAndConditions</value>
      <webElementGuid>c7d0dfdb-4a24-43ed-a0ac-ada7064683c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isTermsAndConditionsAccepted</value>
      <webElementGuid>035de519-723f-460a-8600-9da2838c1a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7ed35bfd-ad31-4494-9184-5693a138616b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>isTermsAndConditionsAccepted</value>
      <webElementGuid>dfa2724d-045f-4028-a08f-14248bb9f5bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>e62fb57a-b001-40b9-9349-166560751d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptTermsAndConditions&quot;)</value>
      <webElementGuid>366d359e-5af7-4b88-8add-ae40434b8916</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptTermsAndConditions']</value>
      <webElementGuid>0886e361-a9f1-4ace-8ab1-b1da9af72a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>7b08451d-daa4-47d1-996e-acba64dcce92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptTermsAndConditions']</value>
      <webElementGuid>fbf50052-820a-47e5-adea-41207aadceb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
