<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Do you accept our terms and condition_457717</name>
   <tag></tag>
   <elementGuidId>67918e95-520e-4e11-85ee-3c89de5c99e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#acceptPrivacyPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='acceptPrivacyPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a3c336c-fccd-4371-841c-6d6a601eac08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c27cff61-d9e2-4a82-9d18-f6cac61ccbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>5ce93778-bf6e-4cd9-9f95-808e5c705128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>acceptPrivacyPolicy</value>
      <webElementGuid>b0b44fcd-c463-4451-90b5-a9502b4a6071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>isPrivacyPolicyAccepted</value>
      <webElementGuid>bf91a77a-a023-41c6-b604-3dae75b9bd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>7a3d2228-be31-41f5-87bd-53a967a46167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>isPrivacyPolicyAccepted</value>
      <webElementGuid>0a645e25-4b8a-4017-9a8b-757e37a1587b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>64a7bb9b-4ddb-4a8e-94d2-4420b2542d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;acceptPrivacyPolicy&quot;)</value>
      <webElementGuid>39ca3c79-0ef0-4b70-8ad6-b6428c823fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='acceptPrivacyPolicy']</value>
      <webElementGuid>bfb303e0-646c-498c-81f4-78a31d24b3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>278cd88f-73cb-4a6e-a742-78f87a5c9c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'acceptPrivacyPolicy']</value>
      <webElementGuid>822ecdb6-62d9-44c2-a783-08c844ae80c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
